--테이블 생성
CREATE TABLE SAMPLE_STUDY2

(
    ID INT,
    NAME VARCHAR(10)
);

CREATE INDEX IDX_SAMPLE ON SAMPLE_STUDY2(ID);

DROP INDEX IDX_SAMPLE;

SELECT *
FROM SAMPLE_STUDY2;

CREATE UNIQUE INDEX IDX_SAMPLE_UKK ON SAMPLE_STUDY2(ID);