--단일행 서브쿼리
SELECT EMP_NAME,
       JOB_CODE,
       DEPT_CODE,
       SALARY
FROM EMPLOYEE E
WHERE SALARY >= (
    SELECT AVG(SALARY)
    FROM EMPLOYEE
    );

--다중행 서브쿼리
SELECT EMP_NAME,
       JOB_CODE,
       DEPT_CODE,
       SALARY
FROM EMPLOYEE
WHERE SALARY IN (
    SELECT MAX(SALARY)
    FROM EMPLOYEE
    GROUP BY DEPT_CODE
    );

--다중행 다중열 서브쿼리
SELECT EMP_ID,
       EMP_NAME,
       JOB_CODE,
       SALARY
FROM EMPLOYEE
WHERE (JOB_CODE, SALARY)IN
      (SELECT JOB_CODE,
              MIN(SALARY)
      FROM EMPLOYEE
      GROUP BY JOB_CODE);

--인라인 뷰
SELECT ROWNUM,
       EMP_NAME,
       SALARY
FROM(
    SELECT *
    FROM EMPLOYEE
    ORDER BY SALARY DESC
    )
WHERE ROWNUM <=5;

--WITH
WITH TOPN_SAL AS(
    SELECT EMP_NAME,
           SALARY
    FROM EMPLOYEE
    ORDER BY SALARY DESC
)
SELECT ROWNUM,
       EMP_NAME,
       SALARY
FROM TOPN_SAL;

--RANK

SELECT RANK() over (ORDER BY SALARY DESC) AS "RANK",
       EMP_NAME,
       SALARY
FROM EMPLOYEE;

SELECT DENSE_RANK() over (ORDER BY SALARY DESC) AS "RANK",
       EMP_NAME,
       SALARY
FROM EMPLOYEE;
