
CREATE TABLE SAMPLE_STUDY
(
    TEST_VARCHAR VARCHAR(10),
    TEST_INT INT
);

--TABLE 수정
ㅑSELECT * FROM SAMPLE_STUDY;

--컬럼 추가하기
ALTER TABLE SAMPLE_STUDY ADD TEST_VARCHAR2 VARCHAR2(15);

--컬럶 수정하기
ALTER TABLE SAMPLE_STUDY MODIFY TEST_VARCHAR2 VARCHAR(5);

--컬럼 삭제
ALTER TABLE SAMPLE_STUDY DROP COLUMN TEST_VARCHAR2;

--테이블 삭제
DROP TABLE SAMPLE_STUDY;

--삭제 확인
--표시되지 않는다.
SELECT *
FROM SAMPLE_STUDY;